import { chromium } from 'playwright-core';
const exe = '/mnt/efs-fullstack/sessions/f7bc37bc-56ba-4700-8d3f-4dffb5c96f90/.agon-env/agent_1/home/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome';
process.env.HOME='/tmp/chrhome'; process.env.XDG_CONFIG_HOME='/tmp/chrhome/.config'; process.env.XDG_CACHE_HOME='/tmp/chrhome/.cache'; process.env.TMPDIR='/tmp';
const browser = await chromium.launchPersistentContext('/tmp/cud', { executablePath: exe, args: ['--no-sandbox','--disable-dev-shm-usage'] });
const page = browser.pages()[0] || await browser.newPage();
const logs=[];
page.on('response', async r=>{ if(r.url().includes('/api/settings')){ const m=r.request().method(); if(m==='PUT'){ try{ const j=await r.json(); logs.push('PUT RESP '+r.status()+': '+JSON.stringify(j)); }catch{} } else logs.push(m+' '+r.status()); } });
await page.goto('https://filebase-library-rzef.arcada.app/login',{waitUntil:'networkidle',timeout:45000}).catch(()=>{});
await page.waitForTimeout(1500);
await page.fill('input[type=email]', 'demo@example.com').catch(()=>{});
await page.fill('input[type=password]', 'password123').catch(()=>{});
await page.click('button[type=submit]').catch(()=>{});
await page.waitForTimeout(2500);
console.log('URL after login:', page.url());
await page.goto('https://filebase-library-rzef.arcada.app/admin/settings',{waitUntil:'networkidle',timeout:45000}).catch(()=>{});
await page.waitForTimeout(2000);
const nameInput = page.locator('input').nth(0);
await nameInput.fill('خلاصة التمريض TEST').catch(e=>console.log('fill err',e.message));
await page.locator('button:has-text("حفظ التغييرات")').first().click().catch(e=>console.log('click err',e.message));
await page.waitForTimeout(2500);
console.log('SETTINGS API LOGS:'); logs.forEach(l=>console.log(' ',l));
const toast = await page.evaluate(()=>{const els=[...document.querySelectorAll('div,p')]; const t=els.find(d=>/تم حفظ|خطأ|error|Error/i.test(d.textContent||'')&&(d.textContent||'').length<160&&d.children.length<4); return t?t.textContent.trim().slice(0,160):'(no toast)';});
console.log('toast/error text:', toast);
await browser.close();
